# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_config.proto',
  package='deepchem.models.tensorflow_models',
  syntax='proto2',
  serialized_pb=_b('\n\x12model_config.proto\x12!deepchem.models.tensorflow_models\"\xd1\x02\n\x0bModelConfig\x12K\n\tparameter\x18\x01 \x03(\x0b\x32\x38.deepchem.models.tensorflow_models.ModelConfig.Parameter\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x1a\xdf\x01\n\tParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\n \x01(\t\x12\x15\n\x0b\x66loat_value\x18\x02 \x01(\x02H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x05H\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x12\x12\n\nfloat_list\x18\x06 \x03(\x02\x12\x10\n\x08int_list\x18\x07 \x03(\x05\x12\x13\n\x0bstring_list\x18\x08 \x03(\t\x12\x11\n\tbool_list\x18\t \x03(\x08\x42\x07\n\x05value')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODELCONFIG_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.description', index=1,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.float_value', index=2,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.int_value', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.string_value', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.bool_value', index=5,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_list', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.float_list', index=6,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_list', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.int_list', index=7,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_list', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.string_list', index=8,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_list', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.bool_list', index=9,
      number=9, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='deepchem.models.tensorflow_models.ModelConfig.Parameter.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=172,
  serialized_end=395,
)

_MODELCONFIG = _descriptor.Descriptor(
  name='ModelConfig',
  full_name='deepchem.models.tensorflow_models.ModelConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameter', full_name='deepchem.models.tensorflow_models.ModelConfig.parameter', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='deepchem.models.tensorflow_models.ModelConfig.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MODELCONFIG_PARAMETER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=395,
)

_MODELCONFIG_PARAMETER.containing_type = _MODELCONFIG
_MODELCONFIG_PARAMETER.oneofs_by_name['value'].fields.append(
  _MODELCONFIG_PARAMETER.fields_by_name['float_value'])
_MODELCONFIG_PARAMETER.fields_by_name['float_value'].containing_oneof = _MODELCONFIG_PARAMETER.oneofs_by_name['value']
_MODELCONFIG_PARAMETER.oneofs_by_name['value'].fields.append(
  _MODELCONFIG_PARAMETER.fields_by_name['int_value'])
_MODELCONFIG_PARAMETER.fields_by_name['int_value'].containing_oneof = _MODELCONFIG_PARAMETER.oneofs_by_name['value']
_MODELCONFIG_PARAMETER.oneofs_by_name['value'].fields.append(
  _MODELCONFIG_PARAMETER.fields_by_name['string_value'])
_MODELCONFIG_PARAMETER.fields_by_name['string_value'].containing_oneof = _MODELCONFIG_PARAMETER.oneofs_by_name['value']
_MODELCONFIG_PARAMETER.oneofs_by_name['value'].fields.append(
  _MODELCONFIG_PARAMETER.fields_by_name['bool_value'])
_MODELCONFIG_PARAMETER.fields_by_name['bool_value'].containing_oneof = _MODELCONFIG_PARAMETER.oneofs_by_name['value']
_MODELCONFIG.fields_by_name['parameter'].message_type = _MODELCONFIG_PARAMETER
DESCRIPTOR.message_types_by_name['ModelConfig'] = _MODELCONFIG

ModelConfig = _reflection.GeneratedProtocolMessageType('ModelConfig', (_message.Message,), dict(

  Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), dict(
    DESCRIPTOR = _MODELCONFIG_PARAMETER,
    __module__ = 'model_config_pb2'
    # @@protoc_insertion_point(class_scope:deepchem.models.tensorflow_models.ModelConfig.Parameter)
    ))
  ,
  DESCRIPTOR = _MODELCONFIG,
  __module__ = 'model_config_pb2'
  # @@protoc_insertion_point(class_scope:deepchem.models.tensorflow_models.ModelConfig)
  ))
_sym_db.RegisterMessage(ModelConfig)
_sym_db.RegisterMessage(ModelConfig.Parameter)


# @@protoc_insertion_point(module_scope)
