package:
  name: {{ environ.get('package_name', 'deepchem') }}
  version: "2.0.0"

source:
    git_url: https://github.com/deepchem/deepchem.git
    git_tag: 2.0.0

build:
  number: 0
  skip: True  # [win]


requirements:
  build:
    - python {{ environ.get('python_version', '3.5') }}
    - setuptools
    - pbr
    - numpy

  run:
    - python {{ environ.get('python_version', '3.5') }}
    - pdbfixer ==1.4
    - mdtraj ==1.9.1
    - joblib ==0.11
    - scikit-learn ==0.19.1
    - networkx ==1.11
    - xgboost ==0.6a2
    - pillow ==4.3.0
    - pandas ==0.22.0
    - {{ environ.get('tensorflow_enabled','tensorflow') }} ==1.5.0
    - nose ==1.3.7
    - nose-timer ==0.7.0
    - flaky ==3.3.0
    - zlib ==1.2.11
    - requests ==2.18.4
    - simdna ==0.4.2
    - jupyter=1.0.0
    - rdkit ==2017.09.1


about:
  home: https://github.com/deepchem/deepchem
  license: MIT
  summary: 'Deep-learning models for Drug Discovery and Quantum Chemistry '
  description: |
    DeepChem aims to provide a high quality open-source toolchain that
    democratizes the use of deep-learning in drug discovery, materials
    science, quantum chemistry, and biology.
  doc_url: https://deepchem.io/
  dev_url: https:/github.com/deepchem/deepchem
