CheckFeaturizer = {
('tox21', 'logreg'):      ['ECFP', 1024],
('tox21', 'tf'):          ['ECFP', 1024],
('tox21', 'tf_robust'):   ['ECFP', 1024],
('tox21', 'rf'):          ['ECFP', 1024],
('tox21', 'irv'):         ['ECFP', 1024],
('tox21', 'graphconv'):   ['GraphConv', 75],
('muv', 'logreg'):        ['ECFP', 1024],
('muv', 'tf'):            ['ECFP', 1024],
('muv', 'tf_robust'):     ['ECFP', 1024],
('muv', 'rf'):            ['ECFP', 1024],
('muv', 'irv'):           ['ECFP', 1024],
('muv', 'graphconv'):     ['GraphConv', 75],
('pcba', 'logreg'):       ['ECFP', 1024],
('pcba', 'tf'):           ['ECFP', 1024],
('pcba', 'tf_robust'):    ['ECFP', 1024],
('pcba', 'rf'):           ['ECFP', 1024],
('pcba', 'irv'):          ['ECFP', 1024],
('pcba', 'graphconv'):    ['GraphConv', 75],
('toxcast', 'logreg'):    ['ECFP', 1024],
('toxcast', 'tf'):        ['ECFP', 1024],
('toxcast', 'tf_robust'): ['ECFP', 1024],
('toxcast', 'rf'):        ['ECFP', 1024],
('toxcast', 'irv'):       ['ECFP', 1024],
('toxcast', 'graphconv'): ['GraphConv', 75],
('sider', 'logreg'):      ['ECFP', 1024],
('sider', 'tf'):          ['ECFP', 1024],
('sider', 'tf_robust'):   ['ECFP', 1024],
('sider', 'rf'):          ['ECFP', 1024],
('sider', 'irv'):         ['ECFP', 1024],
('sider', 'graphconv'):   ['GraphConv', 75],
('clintox', 'logreg'):    ['ECFP', 1024],
('clintox', 'tf'):        ['ECFP', 1024],
('clintox', 'tf_robust'): ['ECFP', 1024],
('clintox', 'rf'):        ['ECFP', 1024],
('clintox', 'irv'):       ['ECFP', 1024],
('clintox', 'graphconv'): ['GraphConv', 75],
('hiv', 'logreg'):        ['ECFP', 1024],
('hiv', 'tf'):            ['ECFP', 1024],
('hiv', 'tf_robust'):     ['ECFP', 1024],
('hiv', 'rf'):            ['ECFP', 1024],
('hiv', 'irv'):           ['ECFP', 1024],
('hiv', 'graphconv'):     ['GraphConv', 75],
('bace_c', 'logreg'):     ['ECFP', 1024],
('bace_c', 'tf'):         ['ECFP', 1024],
('bace_c', 'tf_robust'):  ['ECFP', 1024],
('bace_c', 'rf'):         ['ECFP', 1024],
('bace_c', 'irv'):        ['ECFP', 1024],
('bace_c', 'graphconv'):  ['GraphConv', 75],

('delaney', 'tf_regression'):   ['ECFP', 1024],
('delaney', 'rf_regression'):   ['ECFP', 1024],
('delaney', 'graphconvreg'):    ['GraphConv', 75],
('sampl', 'tf_regression'):     ['ECFP', 1024],
('sampl', 'rf_regression'):     ['ECFP', 1024],
('sampl', 'graphconvreg'):      ['GraphConv', 75],
('nci', 'tf_regression'):       ['ECFP', 1024],
('nci', 'rf_regression'):       ['ECFP', 1024],
('nci', 'graphconvreg'):        ['GraphConv', 75],
('chembl', 'tf_regression'):    ['ECFP', 1024],
('chembl', 'rf_regression'):    ['ECFP', 1024],
('chembl', 'graphconvreg'):     ['GraphConv', 75],
('bace_r', 'tf_regression'):    ['ECFP', 1024],
('bace_r', 'rf_regression'):    ['ECFP', 1024],
('bace_r', 'graphconvreg'):     ['GraphConv', 75],
('clearance', 'tf_regression'): ['ECFP', 1024],
('clearance', 'rf_regression'): ['ECFP', 1024],
('clearance', 'graphconvreg'):  ['GraphConv', 75],
('hopv', 'tf_regression'):      ['ECFP', 1024],
('hopv', 'rf_regression'):      ['ECFP', 1024],
('hopv', 'graphconvreg'):       ['GraphConv', 75],
('lipo', 'tf_regression'):      ['ECFP', 1024],
('lipo', 'rf_regression'):      ['ECFP', 1024],
('lipo', 'graphconvreg'):       ['GraphConv', 75],
('ppb', 'tf_regression'):       ['ECFP', 1024],
('ppb', 'rf_regression'):       ['ECFP', 1024],
('ppb', 'graphconvreg'):        ['GraphConv', 75],

('kaggle', 'tf_regression'):  [None, 14293],
('kaggle', 'rf_regression'):  [None, 14293],
('pdbbind', 'tf_regression'): ['grid', 2052],
('pdbbind', 'rf_regression'): ['grid', 2052],
('qm7', 'tf_regression_ft'):  [None, [23, 23]],
('qm7b', 'tf_regression_ft'): [None, [23, 23]],
('qm8', 'tf_regression_ft'):  [None, [26, 26]],
('qm9', 'tf_regression_ft'):  [None, [29, 29]]
}

CheckSplit = {
'tox21':  ['index', 'random', 'scaffold', 'butina'],
'muv':    ['index', 'random', 'scaffold'], 
'pcba':   ['index', 'random', 'scaffold'],
'sider':  ['index', 'random', 'scaffold'],
'toxcast':['index', 'random', 'scaffold'], 
'clintox':['index', 'random', 'scaffold'], 
'hiv':    ['index', 'random', 'scaffold', 'butina'],
'bace_c': ['index', 'random'],
'delaney':['index', 'random', 'scaffold'],
'sampl':  ['index', 'random', 'scaffold'],
'nci':    ['index', 'random', 'scaffold'],
'chembl': ['index', 'random', 'scaffold', 'year'],
'bace_r': ['index', 'random'],
'clearance': ['index', 'random', 'scaffold'],
'hopv':    ['index', 'random', 'scaffold', 'butina'],
'lipo':    ['index', 'random', 'scaffold'],
'ppb':    ['index', 'random', 'scaffold'],
'kaggle': ['index'], # already splitted, no splitter required
'pdbbind':['index', 'random'],
'qm7':    ['index', 'random', 'stratified'],
'qm7b':   ['index', 'random', 'stratified'],
'qm8':    ['index', 'random', 'stratified'],
'qm9':    ['index', 'random', 'stratified']
}
