"""Point-group symmetry utilities for RFDiffusion All-Atom.

RFdiffusion enforces point-group symmetry on generated multi-chain
assemblies by projecting per-residue frames onto the symmetric subspace
defined by a group ``G`` after every denoising step [Watson2023]_: if
``L`` residues form ``|G|`` copies of an asymmetric unit of size ``L /
|G|``, every copy's frame is averaged (in a common reference frame) with
the corresponding frames of every other copy, then each averaged frame is
re-expressed in its own copy's orientation. This keeps every copy related
to the others by the exact same rigid motion throughout sampling, instead
of letting them drift apart.

This module provides the rotation matrices for the five point-group
families RFdiffusion All-Atom supports -- cyclic (:math:`C_n`), dihedral
(:math:`D_n`), tetrahedral (:math:`T`), octahedral (:math:`O`), and
icosahedral (:math:`I`) [Krishna2024]_ -- plus :func:`symmetrize_coords`
and :func:`symmetrize_frames`, which do the projection described above.

:math:`C_n` and :math:`D_n` are built directly from their closed-form
rotation formulas. :math:`T`, :math:`O`, and :math:`I` are generated by
group closure from two generator rotations each (a standard technique for
finite point groups) rather than a hardcoded table of matrices, and the
resulting group order is checked against the known value (12, 24, and 60
respectively) as a self-consistency check on the generators.

References
----------
.. [Watson2023] Watson, J. L., et al. "De novo design of protein
   structure and function with RFdiffusion." Nature 620 (2023)
   1089-1100.
.. [Krishna2024] Krishna, R., et al. "Generalized biomolecular modeling
   and design with RoseTTAFold All-Atom." Science 384 (2024) eadl2528.

Notes
-----
This module requires PyTorch to be installed.
"""

import math
from typing import Optional

try:
    import torch
except ModuleNotFoundError:
    raise ImportError('rfdiffusion_symmetry requires PyTorch to be installed.')

from deepchem.models.torch_models.rfdiffusion_frames import (
    apply_inverse_rigid,
    apply_rigid,
    so3_exp_map,
    so3_log_map,
)

__all__ = [
    'cyclic_group',
    'dihedral_group',
    'tetrahedral_group',
    'octahedral_group',
    'icosahedral_group',
    'symmetrize_coords',
    'symmetrize_frames',
]


def _axis_angle_rotation(axis, angle: float) -> torch.Tensor:
    """Build a single rotation matrix from an axis (list of 3 floats) and angle."""
    axis_t = torch.nn.functional.normalize(torch.tensor(axis,
                                                        dtype=torch.float64),
                                           dim=-1)
    tangent = (angle * axis_t).unsqueeze(0)
    return so3_exp_map(tangent.float())[0]


def _group_closure(generators,
                   order: int,
                   tol: float = 1e-4,
                   max_iters: int = 500) -> torch.Tensor:
    """Generate a finite rotation group by closure from generator matrices.

    Repeatedly left-multiplies every generator onto every group element
    found so far, until no new (up to ``tol``) rotation matrices appear
    or ``order`` elements have been found.
    """
    group = [torch.eye(3, dtype=torch.float64)]
    frontier = list(group)
    iters = 0
    while frontier and len(group) < order and iters < max_iters:
        new_frontier = []
        for g in frontier:
            for gen in generators:
                candidate = torch.matmul(gen.double(), g)
                if not any(
                        torch.allclose(candidate, existing, atol=tol)
                        for existing in group):
                    group.append(candidate)
                    new_frontier.append(candidate)
        frontier = new_frontier
        iters += 1
    if len(group) != order:
        raise RuntimeError(
            f'Group closure produced {len(group)} elements, expected '
            f'{order}. The generator rotations may be wrong.')
    return torch.stack(group).float()


def cyclic_group(n: int) -> torch.Tensor:
    """Rotation matrices of the cyclic point group :math:`C_n`.

    Parameters
    ----------
    n : int
        Symmetry order; must be >= 1.

    Returns
    -------
    torch.Tensor
        Rotation matrices of shape ``(n, 3, 3)``, rotations of
        ``2*pi*k/n`` about the z-axis for ``k = 0, ..., n-1``.

    Examples
    --------
    >>> from deepchem.models.torch_models.rfdiffusion_symmetry import (
    ...     cyclic_group)
    >>> group = cyclic_group(3)
    >>> group.shape
    torch.Size([3, 3, 3])
    """
    if n < 1:
        raise ValueError('n must be at least 1.')
    angles = torch.arange(n, dtype=torch.float64) * (2 * math.pi / n)
    tangents = torch.stack(
        [torch.zeros_like(angles),
         torch.zeros_like(angles), angles], dim=-1)
    return so3_exp_map(tangents.float())


def dihedral_group(n: int) -> torch.Tensor:
    """Rotation matrices of the dihedral point group :math:`D_n`.

    Parameters
    ----------
    n : int
        Symmetry order of the underlying cyclic subgroup; must be >= 1.

    Returns
    -------
    torch.Tensor
        Rotation matrices of shape ``(2n, 3, 3)``: the ``n`` rotations of
        :func:`cyclic_group` about the z-axis, followed by those same
        rotations composed with a 180-degree flip about the x-axis.

    Examples
    --------
    >>> from deepchem.models.torch_models.rfdiffusion_symmetry import (
    ...     dihedral_group)
    >>> group = dihedral_group(2)
    >>> group.shape
    torch.Size([4, 3, 3])
    """
    if n < 1:
        raise ValueError('n must be at least 1.')
    c = cyclic_group(n)
    flip = torch.tensor([[1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0, -1.0]])
    return torch.cat([c, torch.matmul(flip, c)], dim=0)


def tetrahedral_group() -> torch.Tensor:
    """Rotation matrices of the chiral tetrahedral point group :math:`T`.

    Generated by closure from a 180-degree rotation about the z-axis and
    a 120-degree rotation about the ``(1, 1, 1)`` body diagonal.

    Returns
    -------
    torch.Tensor
        Rotation matrices of shape ``(12, 3, 3)``.

    Examples
    --------
    >>> from deepchem.models.torch_models.rfdiffusion_symmetry import (
    ...     tetrahedral_group)
    >>> tetrahedral_group().shape
    torch.Size([12, 3, 3])
    """
    gen1 = _axis_angle_rotation([0.0, 0.0, 1.0], math.pi)
    gen2 = _axis_angle_rotation([1.0, 1.0, 1.0], 2 * math.pi / 3)
    return _group_closure([gen1, gen2], order=12)


def octahedral_group() -> torch.Tensor:
    """Rotation matrices of the chiral octahedral point group :math:`O`.

    Generated by closure from 90-degree rotations about the z-axis and
    the x-axis.

    Returns
    -------
    torch.Tensor
        Rotation matrices of shape ``(24, 3, 3)``.

    Examples
    --------
    >>> from deepchem.models.torch_models.rfdiffusion_symmetry import (
    ...     octahedral_group)
    >>> octahedral_group().shape
    torch.Size([24, 3, 3])
    """
    gen1 = _axis_angle_rotation([0.0, 0.0, 1.0], math.pi / 2)
    gen2 = _axis_angle_rotation([1.0, 0.0, 0.0], math.pi / 2)
    return _group_closure([gen1, gen2], order=24)


def icosahedral_group() -> torch.Tensor:
    """Rotation matrices of the chiral icosahedral point group :math:`I`.

    Generated by closure from a 72-degree rotation about a 5-fold vertex
    axis (using the golden ratio, the standard icosahedron vertex
    coordinate) and a 120-degree rotation about the ``(1, 1, 1)`` 3-fold
    face axis.

    Returns
    -------
    torch.Tensor
        Rotation matrices of shape ``(60, 3, 3)``.

    Examples
    --------
    >>> from deepchem.models.torch_models.rfdiffusion_symmetry import (
    ...     icosahedral_group)
    >>> icosahedral_group().shape
    torch.Size([60, 3, 3])
    """
    phi = (1.0 + 5.0**0.5) / 2.0
    gen1 = _axis_angle_rotation([0.0, 1.0, phi], 2 * math.pi / 5)
    gen2 = _axis_angle_rotation([1.0, 1.0, 1.0], 2 * math.pi / 3)
    return _group_closure([gen1, gen2], order=60)


def symmetrize_coords(coords: torch.Tensor,
                      group: torch.Tensor,
                      center: Optional[torch.Tensor] = None) -> torch.Tensor:
    """Project point-cloud copies onto the symmetric subspace of a group.

    Every copy is transformed back into a shared reference frame (undoing
    its group rotation about ``center``), averaged across copies, and the
    averaged asymmetric unit is re-expressed in each copy's own
    orientation.

    Parameters
    ----------
    coords : torch.Tensor
        Points for every copy of the asymmetric unit, shape ``(G, L,
        3)`` where ``G = group.shape[0]``.
    group : torch.Tensor
        Rotation matrices of shape ``(G, 3, 3)``, e.g. from
        :func:`cyclic_group`.
    center : torch.Tensor, optional
        Symmetry axis origin, shape ``(3,)``. Defaults to the centroid
        of every point across every copy.

    Returns
    -------
    torch.Tensor
        Symmetrized points, same shape as ``coords``.

    Examples
    --------
    >>> import torch
    >>> from deepchem.models.torch_models.rfdiffusion_symmetry import (
    ...     cyclic_group, symmetrize_coords)
    >>> group = cyclic_group(3)
    >>> coords = torch.randn(3, 4, 3)
    >>> sym = symmetrize_coords(coords, group)
    >>> sym.shape
    torch.Size([3, 4, 3])
    >>> # Symmetrizing an already-symmetric input is a no-op.
    >>> asu = torch.randn(4, 3)
    >>> exact = torch.matmul(asu, group.transpose(-1, -2))
    >>> bool(torch.allclose(symmetrize_coords(exact, group), exact, atol=1e-5))
    True
    """
    g_size, length = coords.shape[0], coords.shape[1]
    if group.shape[0] != g_size:
        raise ValueError(
            f'coords has {g_size} copies but group has {group.shape[0]} '
            f'elements.')
    if center is None:
        center = coords.reshape(-1, 3).mean(dim=0)
    center_expanded = center.expand(g_size, length, 3)
    group_expanded = group[:, None].expand(g_size, length, 3, 3)

    local = apply_inverse_rigid(group_expanded, center_expanded, coords)
    mean_local = local.mean(dim=0, keepdim=True).expand(g_size, length, 3)
    return apply_rigid(group_expanded, center_expanded, mean_local)


def symmetrize_frames(rotations: torch.Tensor,
                      translations: torch.Tensor,
                      group: torch.Tensor,
                      center: Optional[torch.Tensor] = None):
    """Project rigid-frame copies onto the symmetric subspace of a group.

    Translations are symmetrized exactly like :func:`symmetrize_coords`.
    Rotations are brought back to a shared reference orientation (left-
    multiplying by each copy's inverse group rotation), averaged in the
    so(3) tangent space with :func:`~deepchem.models.torch_models.rfdiffusion_frames.so3_log_map`
    (a standard small-angle approximation to a proper rotation average),
    mapped back to SO(3), and re-expressed in each copy's orientation.

    Parameters
    ----------
    rotations : torch.Tensor
        Frame rotations for every copy, shape ``(G, L, 3, 3)``.
    translations : torch.Tensor
        Frame origins for every copy, shape ``(G, L, 3)``.
    group : torch.Tensor
        Rotation matrices of shape ``(G, 3, 3)``.
    center : torch.Tensor, optional
        Symmetry axis origin, shape ``(3,)``. Defaults to the centroid
        of every translation across every copy.

    Returns
    -------
    sym_rotations : torch.Tensor
        Symmetrized rotations, shape ``(G, L, 3, 3)``.
    sym_translations : torch.Tensor
        Symmetrized translations, shape ``(G, L, 3)``.

    Examples
    --------
    >>> import torch
    >>> from deepchem.models.torch_models.rfdiffusion_frames import (
    ...     make_identity_rigid)
    >>> from deepchem.models.torch_models.rfdiffusion_symmetry import (
    ...     cyclic_group, symmetrize_frames)
    >>> group = cyclic_group(4)
    >>> R, t = make_identity_rigid((4, 5))
    >>> sym_R, sym_t = symmetrize_frames(R, t, group)
    >>> sym_R.shape, sym_t.shape
    (torch.Size([4, 5, 3, 3]), torch.Size([4, 5, 3]))
    """
    g_size, length = rotations.shape[0], rotations.shape[1]
    if group.shape[0] != g_size:
        raise ValueError(f'rotations has {g_size} copies but group has '
                         f'{group.shape[0]} elements.')

    sym_translations = symmetrize_coords(translations, group, center)

    group_expanded = group[:, None].expand(g_size, length, 3, 3)
    local_rotations = torch.matmul(group_expanded.transpose(-1, -2), rotations)
    tangents = so3_log_map(local_rotations)
    mean_tangent = tangents.mean(dim=0, keepdim=True)
    mean_local_rotation = so3_exp_map(mean_tangent).expand(g_size, length, 3, 3)
    sym_rotations = torch.matmul(group_expanded, mean_local_rotation)

    return sym_rotations, sym_translations
