import unittest

import deepchem as dc
import numpy as np
from deepchem.splits.splitters import ScaffoldSplitter


class TestScaffoldSplitter(unittest.TestCase):

    @staticmethod
    def _make_dataset():
        smiles = np.array([
            "c1ccccc1",
            "Cc1ccccc1",
            "Oc1ccccc1",
            "Nc1ccccc1",
            "c1ccncc1",
            "c1ncccc1",
            "c1cnccc1",
            "C1CCCCC1",
            "C1CCCC1",
            "C1CCNCC1",
            "c1ccc2ccccc2c1",
            "c1ccc2ncccc2c1",
        ])
        X = np.zeros((len(smiles), 1))
        y = np.zeros((len(smiles), 1))
        return dc.data.NumpyDataset(X=X, y=y, ids=smiles)

    def test_scaffolds(self):
        tox21_tasks, tox21_datasets, transformers = \
          dc.molnet.load_tox21(featurizer='GraphConv')
        train_dataset, valid_dataset, test_dataset = tox21_datasets

        splitter = ScaffoldSplitter()
        scaffolds_separate = splitter.generate_scaffolds(train_dataset)
        scaffolds_train, scaffolds_valid, _ = splitter.split(train_dataset)

        # The amount of datapoints has to be the same
        data_cnt = sum([len(sfd) for sfd in scaffolds_separate])
        self.assertTrue(data_cnt == train_dataset.X.shape[0])

        # The number of scaffolds generated by the splitter
        # has to be smaller or equal than number of total molecules
        scaffolds_separate_cnt = len(scaffolds_separate)
        self.assertTrue(scaffolds_separate_cnt <= train_dataset.X.shape[0])

    def test_generate_scaffold(self):
        from deepchem.splits.splitters import _generate_scaffold
        valid_smiles = r's1cc(nc1\[N]=C(\N)N)C'
        scaffold = _generate_scaffold(valid_smiles)
        self.assertTrue(scaffold == 'c1cscn1')

        # Invalid because valence for atom 5 N is greater than permitted (4)
        invalid_smiles = r's1cc(nc1\[NH]=C(\N)N)C'
        scaffold = _generate_scaffold(invalid_smiles)
        self.assertIsNone(scaffold)

    def test_shuffle_false_keeps_existing_behavior(self):
        dataset = self._make_dataset()
        splitter = ScaffoldSplitter()

        split_default = splitter.split(dataset, seed=7)
        split_explicit_false = splitter.split(dataset, seed=7, shuffle=False)

        self.assertEqual(split_default, split_explicit_false)

    def test_shuffle_true_is_deterministic_with_seed(self):
        dataset = self._make_dataset()
        splitter = ScaffoldSplitter()

        split_a = splitter.split(dataset, seed=7, shuffle=True)
        split_b = splitter.split(dataset, seed=7, shuffle=True)

        self.assertEqual(split_a, split_b)

    def test_shuffle_flag_changes_split_order(self):
        dataset = self._make_dataset()
        splitter = ScaffoldSplitter()

        split_unshuffled = splitter.split(dataset, seed=7, shuffle=False)
        split_shuffled = splitter.split(dataset, seed=7, shuffle=True)

        self.assertNotEqual(split_unshuffled, split_shuffled)
