"""
Making it easy to import in classes.
"""
from deepchem.feat.base_featurizers import Featurizer
from deepchem.feat.base_featurizers import MolecularFeaturizer
from deepchem.feat.base_featurizers import ComplexFeaturizer
from deepchem.feat.base_featurizers import UserDefinedFeaturizer
from deepchem.feat.graph_features import ConvMolFeaturizer
from deepchem.feat.graph_features import WeaveFeaturizer
from deepchem.feat.circular_fingerprint import CircularFingerprint
from deepchem.feat.coulomb_matrices_featurizers import CoulombMatrix
from deepchem.feat.coulomb_matrices_featurizers import CoulombMatrixEig
from deepchem.feat.bp_symmetry_function_input import BPSymmetryFunctionInput
from deepchem.feat.rdkit_descriptors import RDKitDescriptors
from deepchem.feat.rdkit_grid_featurizer import RdkitGridFeaturizer
from deepchem.feat.binding_pocket_featurizer import BindingPocketFeaturizer
from deepchem.feat.one_hot_featurizer import OneHotFeaturizer
from deepchem.feat.raw_featurizer import RawFeaturizer
from deepchem.feat.atomic_coordinates_featurizers import AtomicCoordinates
from deepchem.feat.atomic_coordinates_featurizers import NeighborListComplexAtomicCoordinates
from deepchem.feat.adjacency_fingerprint import AdjacencyFingerprint
from deepchem.feat.smiles_to_image import SmilesToImage
from deepchem.feat.smiles_to_seq import SmilesToSeq
from deepchem.feat.materials_featurizers import ElementPropertyFingerprint
from deepchem.feat.materials_featurizers import SineCoulombMatrix
from deepchem.feat.materials_featurizers import StructureGraphFeaturizer
